# Copyright (C) 2022 Ibrahem Mouhamad
#
# SPDX-License-Identifier: MIT

FROM node:lts-slim AS autocs-ui

ENV TERM=xterm \
    LANG='C.UTF-8'  \
    LC_ALL='C.UTF-8'

# Install dependencies
COPY package.json /tmp/
COPY ui/package.json /tmp/ui/
COPY yarn.lock /tmp/

# Install common dependencies
WORKDIR /tmp/
RUN yarn install --ignore-scripts

# Build source code
COPY ui/ /tmp/ui/
RUN yarn run build:ui

FROM nginx:mainline-alpine
# Replace default.conf configuration to remove unnecessary rules
RUN sed -i "s/}/application\/wasm wasm;\n}/g" /etc/nginx/mime.types
COPY ui/react_nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=autocs-ui /tmp/ui/build /usr/share/nginx/html/
