# Copyright (C) 2022 Ibrahem Mouhamad
#
# SPDX-License-Identifier: MIT

FROM maven:3.8.5-openjdk-17 AS build-image

COPY core /tmp/core/
WORKDIR /tmp/core
RUN mvn clean install

COPY engine /tmp/engine/
WORKDIR /tmp/engine
RUN mvn clean install -Pprod

FROM openjdk:17-slim-buster AS autocs_engine
COPY --from=build-image /tmp/engine/target/engine-0.0.1 app.jar

RUN sh -c 'touch /app.jar'

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
